import './globals.css'
import '@repo/ui/styles.css'
import type { Metadata } from 'next'
import localFont from 'next/font/local'
import { HeroUIProvider } from '@heroui/system'
import { Column } from '@repo/ui/components/Layout'
import { NaverMapProvider } from '@/app/NaverMapProvider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const pretendard = localFont({
  src: [
    {
      path: '../../public/fonts/Pretendard-Thin-Subset.woff2',
      weight: '100',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Pretendard-ExtraLight-Subset.woff2',
      weight: '200',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Pretendard-Light-Subset.woff2',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Pretendard-Regular-Subset.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Pretendard-Medium-Subset.woff2',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Pretendard-SemiBold-Subset.woff2',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Pretendard-Bold-Subset.woff2',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Pretendard-ExtraBold-Subset.woff2',
      weight: '800',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Pretendard-Black-Subset.woff2',
      weight: '900',
      style: 'normal',
    },
  ],
  display: 'swap',
  variable: '--font-pretendard',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='ko' suppressHydrationWarning={true}>
      <body className={pretendard.className}>
        <HeroUIProvider>
          <NaverMapProvider>
            <div className={'flex h-svh justify-center bg-[#FEFCF9]'}>
              <Column className={'relative w-full max-w-[450px] bg-white'}>
                {children}
              </Column>
            </div>
          </NaverMapProvider>
        </HeroUIProvider>
      </body>
    </html>
  )
}
