import '@repo/ui/styles.css'
import './globals.css'
import type { Metadata } from 'next'
import QueryProvider from './QueryClientProvider'
import localFont from 'next/font/local'

export const metadata: Metadata = {
  title: 'Create Turborepo',
  description: 'Generated by create turbo',
}

const pretendard = localFont({
  src: '../public/fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='ko'>
      <body className={pretendard.className}>
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  )
}
